# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/packrat/src"
  - "$TRAVIS_BUILD_DIR/packrat/lib"
  packages: true

git:
  depth: 3

env:
  global:
    - secure: GITHUB_PAT

r_packages:
 - matchingR
 - readr
 - dplyr
 - tibble
 - DT
 - rmarkdown

install:
- R -e "0" --args --bootstrap-packrat