# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
 - oldrel
 - release
 - devel

cache: packages
sudo: false

warnings_are_errrors: false

cache:
 directories:
  -$TRAVIS_BUILD_DIR/packrat/src
  -$TRAVIS_BUILD_DIR/lib
 packages: true